### ISSUE TITLE
Использование SHA1

### ISSUE THREAD

**Issue by Amadeus899** [rarimo/FreedomTool#5]
Видно что в исходниках есть код с SHA1, однако, судя по всему, он нигде не используется. Возможно стоит их убрать, а там где он используется, заменить на sha2? Ибо первая версия не рекомендована к использованию из-за вопросов безопасности

**Comment by ivanlele** [comment]
Hi, could you please provide us a link to a source file that uses SHA1?

**Comment by Amadeus899** [comment]
Have already received an answer from [this](https://github.com/rarimo/passport-identity-provider/issues/5) issue. So it seems legit. Closing this one as well
